//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyDataView
    {
        public int PolicyId { get; set; }
        public int ControlNo { get; set; }
        public byte PolicyTypeId { get; set; }
        public int CustomerId { get; set; }
        public string CustomerType { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string NameInPolicy { get; set; }
        public string AddressInPolicy { get; set; }
        public byte InsureCompanyId { get; set; }
        public string ClusterCode { get; set; }
        public string ClusterName { get; set; }
        public Nullable<byte> CoverNoteIssueType { get; set; }
        public string CoverNotePrefix { get; set; }
        public Nullable<long> CoverNoteNo { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> IssueTime { get; set; }
        public Nullable<System.DateTime> PolicyStartDate { get; set; }
        public Nullable<System.DateTime> PolicyEndDate { get; set; }
        public short FinancerId { get; set; }
        public byte PreviousInsureCompanyId { get; set; }
        public string PreviousPolicyNo { get; set; }
        public Nullable<System.DateTime> PreviousExpiryDate { get; set; }
        public string InspectionNo { get; set; }
        public byte InspectionCompanyId { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public Nullable<System.DateTime> InspectionTime { get; set; }
        public string NomineeName { get; set; }
        public byte NomineeRelationShipId { get; set; }
        public Nullable<byte> NomineeAge { get; set; }
        public Nullable<byte> NomineeGender { get; set; }
        public Nullable<int> EndorseGrossPremium { get; set; }
        public Nullable<int> TotalGrossPremium { get; set; }
        public byte NoofYearId { get; set; }
        public short ManufacturerId { get; set; }
        public short ModelId { get; set; }
        public short VariantId { get; set; }
        public string FuelType { get; set; }
        public Nullable<int> SeatingCapacity { get; set; }
        public Nullable<int> CubicCapacity { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> GVW { get; set; }
        public Nullable<int> Exshowroom { get; set; }
        public short MakeYearId { get; set; }
        public string RegistrationNo { get; set; }
        public string EngineNo { get; set; }
        public string ChassisNo { get; set; }
        public short RTOZoneId { get; set; }
        public byte VehicleClassId { get; set; }
        public Nullable<int> GrossPremium { get; set; }
        public Nullable<int> VehicleIDV { get; set; }
        public Nullable<int> CNGIDV { get; set; }
        public Nullable<int> AssessoriesIDV { get; set; }
        public Nullable<int> TotalIDV { get; set; }
        public Nullable<int> OD { get; set; }
        public Nullable<int> EndorseOD { get; set; }
        public Nullable<int> TotalOD { get; set; }
        public int NCBId { get; set; }
        public Nullable<decimal> SpecialDiscount { get; set; }
        public string FVoucherNo { get; set; }
        public string SVoucherNo { get; set; }
        public string TVoucherNo { get; set; }
        public Nullable<int> ShortAmt1 { get; set; }
        public Nullable<int> ShortAmt2 { get; set; }
        public Nullable<int> ShortAmt3 { get; set; }
        public Nullable<int> ShortFallTotal { get; set; }
        public string CDVoucherNo { get; set; }
        public Nullable<int> CashDiscountAmt { get; set; }
        public Nullable<decimal> Loading { get; set; }
        public short AddonRiderId { get; set; }
        public string AddonPlanDetail { get; set; }
        public short TeleCallerId { get; set; }
        public short ReferenceId { get; set; }
        public string BusinessDoneBy { get; set; }
        public short FOSId { get; set; }
        public int DSAId { get; set; }
        public string PolicyRemarks { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public Nullable<byte> Flag1 { get; set; }
        public Nullable<byte> Flag2 { get; set; }
        public Nullable<byte> IsVerified { get; set; }
        public int PolicyCancelReasonId { get; set; }
        public Nullable<byte> IRDACommissionReceived { get; set; }
        public string MonthCycle { get; set; }
        public Nullable<byte> DSACommissionReceived { get; set; }
        public string commMonth { get; set; }
        public Nullable<byte> IsConverted { get; set; }
        public byte BranchId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public byte PolicyStatusId { get; set; }
        public Nullable<System.DateTime> PolicyCancelDate { get; set; }
        public Nullable<byte> ReceivedStatusId { get; set; }
        public Nullable<decimal> ServiceTax { get; set; }
        public string CustomerEmail1 { get; set; }
        public Nullable<int> AddonOD { get; set; }
        public Nullable<int> LoyaltyCounter { get; set; }
        public Nullable<int> RenewalDone { get; set; }
        public Nullable<int> RenewControlNo { get; set; }
        public int PreviousPolicyId { get; set; }
        public Nullable<int> PreviousControlNo { get; set; }
        public string CustomerPAN { get; set; }
        public string GSTIN { get; set; }
        public Nullable<int> TPPremium { get; set; }
        public string AadhaarNo { get; set; }
        public short DSAManageBy { get; set; }
        public int ChequeBouncePolicyId { get; set; }
        public Nullable<int> ReinstateAllow { get; set; }
        public Nullable<System.DateTime> CustomerDOB { get; set; }
        public string CustomerMobile1 { get; set; }
        public string CustomerPhone1 { get; set; }
        public Nullable<System.DateTime> PolicyStartDateOD { get; set; }
        public Nullable<System.DateTime> PolicyEndDateOD { get; set; }
        public short PolicyTermId { get; set; }
        public byte NoofYearODId { get; set; }
        public string CustomerContact { get; set; }
        public Nullable<int> AkgSlipNo { get; set; }
        public Nullable<System.DateTime> AkgSlipIssueDate { get; set; }
        public string PolicyNoOD { get; set; }
        public Nullable<int> InsureCompanyODId { get; set; }
        public Nullable<short> TPnotwithUs { get; set; }
        public Nullable<short> VehicleUsageId { get; set; }
        public Nullable<short> CommissionPayTypeId { get; set; }
        public Nullable<int> CommissionablePremium { get; set; }
        public Nullable<short> DiffPrevODData { get; set; }
        public string PolicyPackageType { get; set; }
        public short PolicyPackageTypeId { get; set; }
    }
}
