//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryCustomerCarePerformance
    {
        public string CallDurationTypeName { get; set; }
        public string CallTypeName { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ControlNo { get; set; }
        public string NameInPolicy { get; set; }
        public Nullable<System.DateTime> PolicyStartDate { get; set; }
        public string RegistrationNo { get; set; }
        public string CompanyName { get; set; }
        public string ModelName { get; set; }
        public string MakeYear { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> DSAId { get; set; }
        public Nullable<int> VerticalId { get; set; }
        public Nullable<int> InsureCompanyId { get; set; }
        public Nullable<int> CallDurationTypeId { get; set; }
        public Nullable<int> CallTypeId { get; set; }
        public string VerticalName { get; set; }
        public Nullable<System.DateTime> LastCallDate { get; set; }
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
    }
}
