//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchClaimsPolicy
    {
        public int PolicyId { get; set; }
        public string ControlNumber { get; set; }
        public string PolicyNumber { get; set; }
        public string RegistrationNumber { get; set; }
        public Nullable<System.DateTime> PolicyExpiryDate { get; set; }
        public string InsuranceCompany { get; set; }
        public string Pos { get; set; }
        public string Branch { get; set; }
        public string Vertical { get; set; }
        public string Customer { get; set; }
        public int CustomerId { get; set; }
        public string Product { get; set; }
        public string Plan { get; set; }
        public string PlanType { get; set; }
        public string ManufacturerName { get; set; }
        public string ModelName { get; set; }
        public string MakeYear { get; set; }
    }
}
