//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchInspection
    {
        public int InspectionId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string CustomerName { get; set; }
        public System.DateTime InspectionDate { get; set; }
        public string RegistrationNumber { get; set; }
        public string MobileNumber { get; set; }
        public string InspectionReferNumber { get; set; }
        public Nullable<System.DateTime> InspectionEntryDate { get; set; }
        public Nullable<int> PosId { get; set; }
        public short InsuranceCompanyId { get; set; }
        public string InsuranceCompanyName { get; set; }
        public Nullable<short> ManufacturerId { get; set; }
        public string ManufacturerName { get; set; }
        public Nullable<short> ModelId { get; set; }
        public string ModelName { get; set; }
        public int InspectionReasonId { get; set; }
        public string InspectionReason { get; set; }
        public string InspectionStatus { get; set; }
        public string InspectionSubStatus { get; set; }
    }
}
