//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchVoucher
    {
        public int VoucherId { get; set; }
        public Nullable<short> VoucherTypeId { get; set; }
        public string PolicyNumber { get; set; }
        public string Customer { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string InstrumentNumber { get; set; }
        public string VoucherNumber { get; set; }
        public Nullable<int> VoucherNumberDigit { get; set; }
        public int VoucherAmount { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public Nullable<bool> IsCancelVerfied { get; set; }
        public Nullable<bool> IsPolicyMapped { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<short> BranchId { get; set; }
        public Nullable<short> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string PosName { get; set; }
        public int PosId { get; set; }
        public string Bank { get; set; }
        public string PaymentMode { get; set; }
        public string VoucherType { get; set; }
        public string TeamMember { get; set; }
        public short TeamMemberId { get; set; }
        public string InsuranceCompany { get; set; }
        public short InsuranceCompanyId { get; set; }
    }
}
