//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBranchServiceProvider
    {
        public int BranchProviderId { get; set; }
        public int ApplicationId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<bool> IsDefaultProvider { get; set; }
        public Nullable<int> CommunicationType { get; set; }
        public string EmailFolderPath { get; set; }
        public string URL { get; set; }
        public string URL2 { get; set; }
        public string URL3 { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string APIKey { get; set; }
        public string Remark { get; set; }
        public string EmailImgPath { get; set; }
    }
}
