//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public int CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public Nullable<short> CustomerTitleId { get; set; }
        public Nullable<short> CustomerContactTitleId { get; set; }
        public string CustomerContact { get; set; }
        public Nullable<int> ClusterId { get; set; }
        public Nullable<short> TerritoryId { get; set; }
        public Nullable<bool> IsCompany { get; set; }
        public Nullable<bool> IsDecisionMaker { get; set; }
        public string CustomerAddress1 { get; set; }
        public Nullable<short> CustomerCityId1 { get; set; }
        public string CustomerPinCode1 { get; set; }
        public string GSTIN1 { get; set; }
        public string CustomerAddress2 { get; set; }
        public Nullable<short> CustomerCityId2 { get; set; }
        public string CustomerPinCode2 { get; set; }
        public string GSTIN2 { get; set; }
        public string CustomerAddress3 { get; set; }
        public Nullable<short> CustomerCityId3 { get; set; }
        public string CustomerPinCode3 { get; set; }
        public string GSTIN3 { get; set; }
        public string CustomerMobile1 { get; set; }
        public Nullable<bool> InactiveMobile1 { get; set; }
        public string CustomerMobile2 { get; set; }
        public Nullable<bool> InactiveMobile2 { get; set; }
        public string CustomerPhone1 { get; set; }
        public Nullable<bool> InactivePhone1 { get; set; }
        public string CustomerPhone2 { get; set; }
        public Nullable<bool> InactivePhone2 { get; set; }
        public Nullable<short> DefaultAddress { get; set; }
        public Nullable<short> DefaultContactNo { get; set; }
        public Nullable<short> DefaultWhatsAppNo { get; set; }
        public string CustomerEmail1 { get; set; }
        public string CustomerEmail2 { get; set; }
        public Nullable<System.DateTime> CustomerDOB { get; set; }
        public Nullable<System.DateTime> CustomerAnniversery { get; set; }
        public Nullable<short> MaritalStatusId { get; set; }
        public Nullable<byte> NoofDependent { get; set; }
        public Nullable<byte> ReferTypeId { get; set; }
        public Nullable<int> POSId { get; set; }
        public Nullable<int> TeamMemberId { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public string PAN { get; set; }
        public string AadhaarNo { get; set; }
        public Nullable<int> BusinessTypeId { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> ProfessionId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<bool> IsMessageSend { get; set; }
        public short BranchId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<short> GenderId { get; set; }
        public string PassportNo { get; set; }
        public Nullable<bool> IsTeamMember { get; set; }
    
        public virtual tblBranch tblBranch { get; set; }
    }
}
