
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PolicyManagement.Infrastructures.EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class tblCommissionCalculation
{

    public int tblCommissionCalculationId { get; set; }

    public string POSName { get; set; }

    public Nullable<int> POsId { get; set; }

    public string CompanyName { get; set; }

    public string PolicyMainType { get; set; }

    public string VehicleMainClass { get; set; }

    public Nullable<decimal> ExShowroomValue { get; set; }

    public Nullable<decimal> ShortFallTotal { get; set; }

    public Nullable<decimal> SpecialDiscount { get; set; }

    public Nullable<decimal> OD { get; set; }

    public string NameInPolicy { get; set; }

    public Nullable<System.DateTime> PolicyStartDate { get; set; }

    public Nullable<int> PolicyId { get; set; }

    public string ControlNo { get; set; }

    public string CoverNoteIssueType { get; set; }

    public string CoverNotePrefix { get; set; }

    public string CoverNoteNo { get; set; }

    public string RegistrationNo { get; set; }

    public Nullable<decimal> GrossPremium { get; set; }

    public Nullable<decimal> TotalIDV { get; set; }

    public Nullable<System.DateTime> IssueDate { get; set; }

    public string PolicyNo { get; set; }

    public string ManufacturerName { get; set; }

    public string ModelName { get; set; }

    public string FuelType { get; set; }

    public Nullable<decimal> CubicCapacity { get; set; }

    public Nullable<int> SeatingCapacity { get; set; }

    public Nullable<int> MakeYear { get; set; }

    public Nullable<decimal> Loading { get; set; }

    public string TeleCaller { get; set; }

    public string FOS { get; set; }

    public string BusinessDoneBy { get; set; }

    public Nullable<int> VerticleId { get; set; }

    public string PolicyPackageType { get; set; }

    public string PolicyTermName { get; set; }

    public string PolicyRemarks { get; set; }

    public string PolicyStatus { get; set; }

    public string EndorsementReason { get; set; }

    public Nullable<System.DateTime> PolicyCancelDate { get; set; }

    public Nullable<decimal> ServiceTax { get; set; }

    public string ReferenceName { get; set; }

    public Nullable<decimal> EndorseGrossPremium { get; set; }

    public Nullable<decimal> EndorseOD { get; set; }

    public string VehicleClass { get; set; }

    public string PolicyType { get; set; }

    public Nullable<int> CommissionMonthId { get; set; }

    public Nullable<int> InsureCompanyId { get; set; }

    public Nullable<int> VehicleMainClassId { get; set; }

    public Nullable<int> PolicyMainTypeId { get; set; }

    public Nullable<int> ManufacturerId { get; set; }

    public Nullable<int> ModelId { get; set; }

    public string AddonPlan { get; set; }

    public Nullable<int> VehicleClassId { get; set; }

    public Nullable<int> PolicyTypeId { get; set; }

    public Nullable<int> PolicyTermId { get; set; }

    public Nullable<int> BranchId { get; set; }

    public Nullable<decimal> NCBPercent { get; set; }

    public Nullable<int> NCBId { get; set; }

    public Nullable<int> FuelTypeId { get; set; }

    public Nullable<decimal> CommisionPercentage { get; set; }

    public Nullable<System.DateTime> AlternateInceptionDate { get; set; }

    public string AlternatePolicyNo { get; set; }

    public string AlternateCompanyName { get; set; }

    public Nullable<int> EndorsementId { get; set; }

    public Nullable<int> EndorsementReasonId { get; set; }

    public Nullable<int> PortabilityId { get; set; }

    public Nullable<decimal> TerrorismPremium { get; set; }

    public Nullable<decimal> TotalSumInsured { get; set; }

    public string Portability { get; set; }

    public Nullable<int> InsuredMaxAge { get; set; }

    public string PlanName { get; set; }

    public Nullable<int> NoofYear { get; set; }

    public Nullable<int> NoofYearId { get; set; }

    public string ProductName { get; set; }

    public Nullable<int> ProductId { get; set; }

}

}
