//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClaimFollowupDetails
    {
        public int Id { get; set; }
        public int ClaimId { get; set; }
        public System.DateTime FollowupDate { get; set; }
        public string FollowupReason { get; set; }
    }
}
