
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PolicyManagement.Infrastructures.EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class tblCommissionSlabNew
{

    public int CommissionSlabNewId { get; set; }

    public string InsureCompanyId { get; set; }

    public string VehicleMainClassId { get; set; }

    public string PolicyMainTypeId { get; set; }

    public Nullable<decimal> SplDiscountFrom { get; set; }

    public Nullable<decimal> SplDiscountUpTo { get; set; }

    public string ManufacturerId { get; set; }

    public string ModelId { get; set; }

    public Nullable<int> ExshowroomValueStart { get; set; }

    public Nullable<int> ExshowroomValueEnd { get; set; }

    public string FuelTypeId { get; set; }

    public Nullable<int> CommissionSlabNewTypeId { get; set; }

    public Nullable<int> CommissionTurnoverTypeId { get; set; }

    public Nullable<int> SlabStart { get; set; }

    public Nullable<int> SlabEnd { get; set; }

    public Nullable<decimal> CommissionPercent { get; set; }

    public Nullable<byte> IsActive { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedTime { get; set; }

    public Nullable<int> ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedTime { get; set; }

    public Nullable<int> VerticalId { get; set; }

    public string ProductId { get; set; }

    public string PolicyTypeId { get; set; }

    public string VehicleClassId { get; set; }

    public string PolicyTermId { get; set; }

    public string BranchId { get; set; }

}

}
