//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCommissionSlab
    {
        public int CommissionSlabId { get; set; }
        public int InsureCompanyId { get; set; }
        public Nullable<int> VehicleMainClassId { get; set; }
        public Nullable<int> PolicyMainTypeId { get; set; }
        public Nullable<decimal> SplDiscountFrom { get; set; }
        public Nullable<decimal> SplDiscountUpTo { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> ExshowroomValueStart { get; set; }
        public Nullable<int> ExshowroomValueEnd { get; set; }
        public Nullable<int> FuelTypeId { get; set; }
        public Nullable<int> CommissionSlabTypeId { get; set; }
        public Nullable<int> CommissionTurnoverTypeId { get; set; }
        public Nullable<int> SlabStart { get; set; }
        public Nullable<int> SlabEnd { get; set; }
        public Nullable<decimal> CommissionPercent { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<int> VerticalId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> PolicyTypeId { get; set; }
        public Nullable<int> VehicleClassId { get; set; }
        public Nullable<int> PolicyTermId { get; set; }
        public string BranchId { get; set; }
    }
}
