//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEndorsementData
    {
        public int EndorsementId { get; set; }
        public int PolicyId { get; set; }
        public short PolicyTypeId { get; set; }
        public Nullable<System.DateTime> EndorsementEntryDate { get; set; }
        public Nullable<System.DateTime> EndorsementDate { get; set; }
        public string EndorsementNo { get; set; }
        public Nullable<short> EndorsementTypeId { get; set; }
        public short EndorsementReasonId { get; set; }
        public Nullable<int> DocumentControlId { get; set; }
        public Nullable<int> AmtODChange { get; set; }
        public Nullable<int> AmtGrossPremiumChange { get; set; }
        public Nullable<int> IDVChange { get; set; }
        public Nullable<short> NewNCBId { get; set; }
        public Nullable<short> NewAddOnPlanId { get; set; }
        public Nullable<short> BounceReasonId { get; set; }
        public Nullable<System.DateTime> BounceDate { get; set; }
        public Nullable<bool> PolicyReinstate { get; set; }
        public Nullable<bool> NCBRecovered { get; set; }
        public Nullable<bool> ReinstateAllow { get; set; }
        public Nullable<short> RTOZoneId { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<int> PremiumIncrease { get; set; }
        public Nullable<int> EndoresementShortfallAmt { get; set; }
        public string EndoresementShortfallVoucherNo { get; set; }
        public string EndorsementRemark { get; set; }
        public Nullable<int> AlternateInsureCompanyId { get; set; }
        public string AlternatePolicyNo { get; set; }
        public Nullable<System.DateTime> AlternateInceptionDate { get; set; }
        public Nullable<short> EndorsementStatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<short> CommMonthCycleId { get; set; }
        public Nullable<short> IRDACommisionReceived { get; set; }
        public Nullable<decimal> ExpectIRDACommPersent { get; set; }
        public Nullable<int> ReceiveIRDACommAmt { get; set; }
        public Nullable<decimal> ReceiveIRDACommPersent { get; set; }
        public Nullable<decimal> ExpectORCCommPersent { get; set; }
        public Nullable<int> ReceiveORCCommAmt { get; set; }
        public Nullable<decimal> ReceiveORCCommPersent { get; set; }
        public Nullable<short> BranchId { get; set; }
        public Nullable<short> DSACommMonthCycleId { get; set; }
        public Nullable<short> DSACommissionReceived { get; set; }
        public Nullable<short> NewManufacturerId { get; set; }
        public Nullable<short> NewModelId { get; set; }
        public Nullable<short> NewVariantId { get; set; }
        public Nullable<short> NewVehicleClassId { get; set; }
        public Nullable<short> NCBRecoveredCancel { get; set; }
    }
}
