//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFireCoverage
    {
        public short FireCoverageId { get; set; }
        public int PolicyId { get; set; }
        public Nullable<int> FireSA { get; set; }
        public Nullable<decimal> FireRate { get; set; }
        public Nullable<int> EarthQuakeSA { get; set; }
        public Nullable<decimal> EarthQuakeRate { get; set; }
        public Nullable<int> STFISA { get; set; }
        public Nullable<decimal> STFIRate { get; set; }
        public Nullable<int> TerrorismSA { get; set; }
        public Nullable<decimal> TerrorismRate { get; set; }
        public Nullable<int> BurglarySA { get; set; }
        public Nullable<decimal> BurglaryRate { get; set; }
        public Nullable<int> MoneySA { get; set; }
        public Nullable<decimal> MoneyRate { get; set; }
        public Nullable<int> BreakDownSA { get; set; }
        public Nullable<decimal> BreakDownRate { get; set; }
        public Nullable<int> PlateGlassSA { get; set; }
        public Nullable<decimal> PlateGlassRate { get; set; }
        public short BranchId { get; set; }
    }
}
