
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PolicyManagement.Infrastructures.EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class tblGmcTerm
{

    public short GmcTermId { get; set; }

    public string CoverageType { get; set; }

    public Nullable<int> NoEmployee { get; set; }

    public Nullable<int> NoDependent { get; set; }

    public Nullable<int> NoLife { get; set; }

    public string Coverage { get; set; }

    public string CooperateLimit { get; set; }

    public string OtherInfo { get; set; }

    public Nullable<int> PolicyId { get; set; }

}

}
