//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGenerator
    {
        public int GeneratorId { get; set; }
        public string tblFieldName { get; set; }
        public Nullable<int> NextNo { get; set; }
        public Nullable<byte> BranchId { get; set; }
        public Nullable<byte> FYId { get; set; }
    }
}
