
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PolicyManagement.Infrastructures.EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class tblLiabilityTerm
{

    public int LiabilityTermId { get; set; }

    public int PolicyId { get; set; }

    public Nullable<long> TotalSumInsured { get; set; }

    public Nullable<int> NoWorker { get; set; }

    public string NatureCoverage { get; set; }

    public string ExcessClause { get; set; }

    public Nullable<short> RiskLocation { get; set; }

    public string OtherInfo { get; set; }

    public Nullable<System.DateTime> RetroSpectiveDate { get; set; }

}

}
