//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMotorPolicyData
    {
        public int PolicyId { get; set; }
        public string ControlNo { get; set; }
        public Nullable<short> LoyaltyCounter { get; set; }
        public string VerticalCode { get; set; }
        public Nullable<bool> RenewalDone { get; set; }
        public Nullable<int> PreviousPolicyId { get; set; }
        public Nullable<int> RenewalPolicyId { get; set; }
        public Nullable<int> ChequeBouncePolicyId { get; set; }
        public Nullable<bool> ReinstateAllow { get; set; }
        public Nullable<short> VerticalSegmentId { get; set; }
        public short VerticalId { get; set; }
        public short PolicyTypeId { get; set; }
        public short VehicleClassId { get; set; }
        public short PolicyTermId { get; set; }
        public string PolicyPackageType { get; set; }
        public short PolicyPackageTypeId { get; set; }
        public short ProductId { get; set; }
        public short PlanId { get; set; }
        public short PlanTypeId { get; set; }
        public int CustomerId { get; set; }
        public string CustomerType { get; set; }
        public string NameInPolicy { get; set; }
        public string AddressInPolicy { get; set; }
        public string PAN { get; set; }
        public string GSTIN { get; set; }
        public string CoverNoteNo { get; set; }
        public Nullable<System.DateTime> CoverNoteDate { get; set; }
        public string AkgSlipNo { get; set; }
        public Nullable<System.DateTime> AkgSlipIssueDate { get; set; }
        public Nullable<short> InsuranceCompanyId { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<System.DateTime> PolicyStartDate { get; set; }
        public Nullable<short> NoofYearId { get; set; }
        public Nullable<System.DateTime> PolicyEndDate { get; set; }
        public Nullable<short> InsuranceCompanyODId { get; set; }
        public string PolicyNoOD { get; set; }
        public Nullable<System.DateTime> PolicyStartDateOD { get; set; }
        public Nullable<short> NoofYearODId { get; set; }
        public Nullable<System.DateTime> PolicyEndDateOD { get; set; }
        public Nullable<int> KMCovered { get; set; }
        public Nullable<int> ExtendedKMCovered { get; set; }
        public Nullable<short> FinancerId { get; set; }
        public Nullable<bool> BlockAgentReassignment { get; set; }
        public Nullable<bool> AgentChange { get; set; }
        public Nullable<bool> NoPreviousPolicy { get; set; }
        public Nullable<short> PreviousInsuranceCompanyId { get; set; }
        public string PreviousPolicyNo { get; set; }
        public Nullable<System.DateTime> PreviousPolicyEndDate { get; set; }
        public string NomineeName { get; set; }
        public short NomineeRelationShipId { get; set; }
        public Nullable<short> NomineeAge { get; set; }
        public Nullable<short> NomineeGenderId { get; set; }
        public string NomineeGuardian { get; set; }
        public short ManufacturerId { get; set; }
        public short ModelId { get; set; }
        public int VariantId { get; set; }
        public string FuelType { get; set; }
        public Nullable<int> CubicCapacity { get; set; }
        public Nullable<int> SeatingCapacity { get; set; }
        public Nullable<int> GVW { get; set; }
        public Nullable<int> KW { get; set; }
        public Nullable<int> Exshowroom { get; set; }
        public short MakeYearId { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<bool> SpecialRegistrationNo { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string EngineNo { get; set; }
        public string ChassisNo { get; set; }
        public short RTOZoneId { get; set; }
        public Nullable<short> VehicleUsageId { get; set; }
        public Nullable<short> VehicleSegmentId { get; set; }
        public Nullable<int> VehicleIDV { get; set; }
        public Nullable<int> ElectricAssessoriesIDV { get; set; }
        public Nullable<int> NonElectricAssessoriesIDV { get; set; }
        public Nullable<int> CNGIDV { get; set; }
        public Nullable<int> TotalIDV { get; set; }
        public Nullable<int> OD { get; set; }
        public Nullable<int> AddonOD { get; set; }
        public Nullable<int> EndorseOD { get; set; }
        public Nullable<int> TotalOD { get; set; }
        public Nullable<int> TPPremium { get; set; }
        public Nullable<int> PassengerCover { get; set; }
        public Nullable<int> EndorseTP { get; set; }
        public Nullable<int> TotalTP { get; set; }
        public Nullable<int> GrossPremium { get; set; }
        public Nullable<int> EndorseGrossPremium { get; set; }
        public Nullable<decimal> GSTRate { get; set; }
        public Nullable<int> TotalGST { get; set; }
        public Nullable<int> TotalGrossPremium { get; set; }
        public Nullable<short> CommissionPayTypeId { get; set; }
        public Nullable<int> CommissionablePremium { get; set; }
        public short NCBId { get; set; }
        public Nullable<decimal> SpecialDiscount { get; set; }
        public Nullable<decimal> Loading { get; set; }
        public short AddonRiderId { get; set; }
        public short TeleCallerId { get; set; }
        public short FOSId { get; set; }
        public int POSId { get; set; }
        public int RenewalPOSId { get; set; }
        public short POSManageBy { get; set; }
        public int ReferenceId { get; set; }
        public string BusinessDoneBy { get; set; }
        public string PolicyRemarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> Flag1 { get; set; }
        public Nullable<bool> Flag2 { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsConverted { get; set; }
        public short BranchId { get; set; }
        public short PolicyStatusId { get; set; }
        public Nullable<int> PolicyCancelReasonId { get; set; }
        public Nullable<System.DateTime> PolicyCancelDate { get; set; }
        public Nullable<short> ReceivedStatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<short> IRDACommMonthCycleId { get; set; }
        public Nullable<short> IRDACommissionReceived { get; set; }
        public Nullable<decimal> ExpectIRDACommPersent { get; set; }
        public Nullable<int> ReceiveIRDACommAmt { get; set; }
        public Nullable<decimal> ReceiveIRDACommPersent { get; set; }
        public Nullable<decimal> ExpectORCCommPersent { get; set; }
        public Nullable<int> ReceiveORCCommAmt { get; set; }
        public Nullable<decimal> ReceiveORCCommPersent { get; set; }
        public Nullable<short> POSCommMonthCycleId { get; set; }
        public Nullable<short> POSCommissionReceived { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<int> NoAdult { get; set; }
        public Nullable<int> NoChild { get; set; }
        public Nullable<System.DateTime> CBStartDate { get; set; }
        public Nullable<short> PortabilityId { get; set; }
        public Nullable<decimal> FamilyDiscount { get; set; }
        public Nullable<decimal> LongTermDiscount { get; set; }
        public Nullable<decimal> SectionDiscount { get; set; }
        public Nullable<decimal> AdditionalDiscount { get; set; }
        public Nullable<int> AddonRiderPremium { get; set; }
        public Nullable<int> NoofDaysHospitalCash { get; set; }
        public Nullable<int> CoverageId { get; set; }
        public Nullable<int> NoofDays { get; set; }
        public Nullable<int> MaxDaysSingleTrip { get; set; }
        public string Occupancy { get; set; }
        public string LineofBusiness { get; set; }
        public Nullable<byte> BasementExposerId { get; set; }
        public Nullable<int> TerrorismPremium { get; set; }
        public Nullable<long> TotalSumInsured { get; set; }
        public Nullable<int> InsuredMaxAge { get; set; }
        public Nullable<byte> StorageRiskId { get; set; }
        public Nullable<byte> VoyageTypeId { get; set; }
        public Nullable<byte> VoyageOverseasTypeId { get; set; }
        public Nullable<byte> CoverageInlandId { get; set; }
        public Nullable<byte> CoverageOverseasId { get; set; }
        public string TransitFromDomestic { get; set; }
        public string TransitToDomestic { get; set; }
        public string TransitFromOverseas { get; set; }
        public string TransitToOverseas { get; set; }
        public Nullable<decimal> MarineRate { get; set; }
        public Nullable<decimal> MiscRate { get; set; }
        public string MiscInfo1 { get; set; }
        public string MiscInfo2 { get; set; }
        public string MiscInfo3 { get; set; }
        public string MiscInfo4 { get; set; }
        public Nullable<int> FlagPostCall { get; set; }
        public Nullable<int> FlagMidCall { get; set; }
        public Nullable<int> FlagPreRenewCall { get; set; }
        public string AddOnSelected { get; set; }
        public string PreviousPolicyPlan { get; set; }
        public Nullable<int> PreviousSumInsured { get; set; }
    }
}
