//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicyTerm
    {
        public short PolicyTermId { get; set; }
        public short VehicleClassId { get; set; }
        public short PolicyTypeId { get; set; }
        public short PolicyPackageTypeId { get; set; }
        public string PolicyPackageType { get; set; }
        public string PolicyTermName { get; set; }
        public int TPYear { get; set; }
        public int ODYear { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    }
}
