//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPOS
    {
        public int POSId { get; set; }
        public string POSCode { get; set; }
        public string POSName { get; set; }
        public short POSManagedBy { get; set; }
        public Nullable<bool> CommunicationSend { get; set; }
        public Nullable<bool> IsBookIssue { get; set; }
        public Nullable<short> POSTitleId { get; set; }
        public Nullable<short> POSLocationId { get; set; }
        public string POSAddress1 { get; set; }
        public Nullable<short> POSCityId1 { get; set; }
        public string POSPinCode1 { get; set; }
        public string POSAddress2 { get; set; }
        public Nullable<short> POSCityId2 { get; set; }
        public string POSPinCode2 { get; set; }
        public string POSPhone1 { get; set; }
        public string POSPhone2 { get; set; }
        public string POSMobile1 { get; set; }
        public string POSMobile2 { get; set; }
        public string POSEmail1 { get; set; }
        public string POSEmail2 { get; set; }
        public Nullable<System.DateTime> POSDOB { get; set; }
        public Nullable<System.DateTime> POSDOJ { get; set; }
        public Nullable<short> CategoryId { get; set; }
        public Nullable<short> TypeId { get; set; }
        public Nullable<bool> IsMotor { get; set; }
        public Nullable<bool> IsHealth { get; set; }
        public Nullable<bool> IsCommercial { get; set; }
        public Nullable<bool> IsLife { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    }
}
