//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPOSContact
    {
        public int POSContactID { get; set; }
        public int POSId { get; set; }
        public string POSContactName { get; set; }
        public string POSContactMobile1 { get; set; }
        public string POSContactMobile2 { get; set; }
        public string POSContactEmailID { get; set; }
        public Nullable<bool> IsMessageSend { get; set; }
        public Nullable<bool> IsMotor { get; set; }
        public Nullable<bool> IsHealth { get; set; }
        public Nullable<bool> IsCommercial { get; set; }
        public Nullable<bool> IsLife { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    }
}
