//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReferenceLead
    {
        public int ReferenceLeadId { get; set; }
        public string ReferenceLeadName { get; set; }
        public string ReferenceLeadAddress { get; set; }
        public string ReferenceLeadPhone1 { get; set; }
        public string ReferenceLeadPhone2 { get; set; }
        public string ReferenceLeadMobile1 { get; set; }
        public string ReferenceLeadMobile2 { get; set; }
        public string ReferenceLeadEmail1 { get; set; }
        public string ReferenceLeadEmail2 { get; set; }
        public Nullable<int> ReferenceLeadTypeId { get; set; }
        public Nullable<int> ReferenceLeadVerticalId { get; set; }
        public Nullable<System.DateTime> TentitiveExpiryDate { get; set; }
        public Nullable<int> InsuranceCompanyId { get; set; }
        public Nullable<int> AssignedTelecallerId { get; set; }
        public Nullable<int> LeadQualityId { get; set; }
        public Nullable<int> ReferenceSourceId { get; set; }
        public string ReferencePersonName { get; set; }
        public string ReferenceLeadRemark { get; set; }
        public Nullable<int> AssignedFOS { get; set; }
        public Nullable<int> ReferBy { get; set; }
        public Nullable<int> TeleCallingFlag { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<short> BranchId { get; set; }
        public Nullable<int> CustType { get; set; }
        public string CustCode { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<short> VehicleClassId { get; set; }
        public Nullable<short> ManufacturerId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<short> MakeYearId { get; set; }
        public Nullable<int> VariantId { get; set; }
        public Nullable<short> FuelTypeId { get; set; }
        public string GSTNo { get; set; }
        public string PANNo { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<short> NCBId { get; set; }
        public Nullable<int> IDV { get; set; }
        public Nullable<int> CC { get; set; }
        public Nullable<int> GVW { get; set; }
        public Nullable<short> Seating { get; set; }
        public Nullable<int> AsseCNGIDV { get; set; }
        public string AddOnPlan { get; set; }
    }
}
