//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeamMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTeamMember()
        {
            this.tblUser = new HashSet<tblUser>();
        }
    
        public short TeamMemberId { get; set; }
        public string TeamMemberName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> LevelNumber { get; set; }
        public Nullable<short> ReportedToId { get; set; }
        public Nullable<short> DepartmentId { get; set; }
        public Nullable<short> DesignationId { get; set; }
        public string TeamMemberCode { get; set; }
        public string TeamMemberAddress { get; set; }
        public string TeamMemberPhone1 { get; set; }
        public string TeamMemberPhone2 { get; set; }
        public string TeamMemberMobile1 { get; set; }
        public string TeamMemberMobile2 { get; set; }
        public string TeamMemberEmail1 { get; set; }
        public string TeamMemberEmail2 { get; set; }
        public Nullable<System.DateTime> TeamMemberDOB { get; set; }
        public Nullable<System.DateTime> TeamMemberDOJ { get; set; }
        public Nullable<bool> IsBookIssue { get; set; }
        public Nullable<short> BranchId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<bool> ISTelecaller { get; set; }
        public Nullable<bool> ISFOS { get; set; }
        public Nullable<bool> IsMotor { get; set; }
        public Nullable<bool> IsHealth { get; set; }
        public Nullable<bool> IsCommercial { get; set; }
        public Nullable<bool> IsLife { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<bool> IsInspection { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
        public virtual tblDesignation tblDesignation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUser> tblUser { get; set; }
    }
}
