//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUploadedDocuments
    {
        public int DocumentId { get; set; }
        public Nullable<int> PolicyId { get; set; }
        public int DocId { get; set; }
        public string Directory { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> InspectionId { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<int> ClaimId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string OriginalFileName { get; set; }
    }
}
