//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoucherDetails
    {
        public int VoucherId { get; set; }
        public string VoucherNo { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public Nullable<int> PolicyId { get; set; }
        public short InsuranceCompanyId { get; set; }
        public string CustomerName { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<short> VerticalId { get; set; }
        public Nullable<short> VoucherTypeId { get; set; }
        public Nullable<short> ReferTypeId { get; set; }
        public Nullable<int> POSId { get; set; }
        public Nullable<int> TeamMemberId { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public Nullable<short> PaymentModeId { get; set; }
        public string TxnInstrumentNo { get; set; }
        public int VoucherAmount { get; set; }
        public Nullable<System.DateTime> TxnInstrumentDate { get; set; }
        public Nullable<short> BankId { get; set; }
        public string AccountUsedforCheque { get; set; }
        public string VoucherRemark { get; set; }
        public string ModificationReason { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<short> VoucherStatusId { get; set; }
        public string CancelReason { get; set; }
        public Nullable<bool> IsCancelVerfied { get; set; }
        public Nullable<bool> IsPolicyMapped { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string ControlNo { get; set; }
        public Nullable<int> BounceAmt { get; set; }
        public Nullable<System.DateTime> BounceDate { get; set; }
        public string BounceReceiptNo { get; set; }
        public Nullable<short> BranchId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    }
}
