//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    
    public partial class Usp_InspectionByPolicyId_Result1
    {
        public int InspectionId { get; set; }
        public System.DateTime InspectionDate { get; set; }
        public string InspectionReason { get; set; }
        public string InspectionStatus { get; set; }
        public string InspectionSubStatus { get; set; }
    }
}
