//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewCustomerCare
    {
        public int CustomerCallDataId { get; set; }
        public string VerticalName { get; set; }
        public string CompanyName { get; set; }
        public string CallTypeName { get; set; }
        public string ModelName { get; set; }
        public string MakeYear { get; set; }
        public string ProductName { get; set; }
        public Nullable<byte> Q1Response { get; set; }
        public string Q1Comment { get; set; }
        public Nullable<byte> Q2Response { get; set; }
        public string Q2Comment { get; set; }
        public Nullable<byte> Q3Response { get; set; }
        public string Q3Comment { get; set; }
        public string Q5Comment { get; set; }
        public Nullable<byte> CallStatusId { get; set; }
        public Nullable<byte> SubStatusId { get; set; }
        public Nullable<System.DateTime> FollowupDate { get; set; }
        public string FinalComment { get; set; }
        public string SubStatusName { get; set; }
        public Nullable<System.DateTime> LastCallDate { get; set; }
        public Nullable<int> CallTypeId { get; set; }
        public Nullable<int> CallDurationTypeId { get; set; }
        public Nullable<byte> Q4Response { get; set; }
        public string Q4Comment { get; set; }
        public Nullable<byte> Q5Response { get; set; }
        public Nullable<int> PolicyId { get; set; }
        public Nullable<int> ControlNo { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string NameInPolicy { get; set; }
        public Nullable<System.DateTime> PolicyStartDate { get; set; }
        public Nullable<int> DSAId { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<int> VerticalId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> InsureCompanyId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> MakeYearId { get; set; }
    }
}
