//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMasterWithMotorPolicy
    {
        public int PolicyId { get; set; }
        public int ControlNo { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<long> CoverNoteNo { get; set; }
        public string CustomerName { get; set; }
        public string InsureCompanyName { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<int> NCBPercentage { get; set; }
        public string DSAName { get; set; }
        public Nullable<int> TotalGrossPremium { get; set; }
        public Nullable<int> OD { get; set; }
        public string AddonRiderName { get; set; }
        public Nullable<System.DateTime> PolicyEndDate { get; set; }
        public Nullable<System.DateTime> PolicyStartDate { get; set; }
        public string ManufacturerName { get; set; }
        public Nullable<int> VerticalSegmentId { get; set; }
        public string VerticalName { get; set; }
        public string ModelName { get; set; }
        public string ProductName { get; set; }
        public string AddonPlanDetail { get; set; }
        public string PolicyStatus { get; set; }
        public string CustomerMobile1 { get; set; }
        public string CustomerMobile2 { get; set; }
        public string CustomerEmail1 { get; set; }
        public string CustomerEmail2 { get; set; }
        public Nullable<int> RenewalDone { get; set; }
        public int VerticleId { get; set; }
        public byte PolicyTypeId { get; set; }
        public int ProductId { get; set; }
        public int PlanId { get; set; }
        public int PlanTypeId { get; set; }
        public string NameInPolicy { get; set; }
        public short ManufacturerId { get; set; }
        public short ModelId { get; set; }
        public short VariantId { get; set; }
        public string FuelType { get; set; }
        public Nullable<int> GrossPremium { get; set; }
        public int DSAId { get; set; }
        public short FOSId { get; set; }
        public byte PolicyStatusId { get; set; }
        public Nullable<int> InsureCompanyId { get; set; }
        public byte BranchId { get; set; }
        public string BusinessDoneBy { get; set; }
        public short MakeYearId { get; set; }
        public string MakeYear { get; set; }
        public string PlanName { get; set; }
        public int CustomerId { get; set; }
        public string PolicyPackageType { get; set; }
        public string PlanTypeName { get; set; }
        public Nullable<byte> InactiveMobile1 { get; set; }
        public short ReferenceId { get; set; }
        public Nullable<bool> IsMessageSend { get; set; }
        public byte NoofYearId { get; set; }
        public short FinancerId { get; set; }
        public short AddonRiderId { get; set; }
        public byte InspectionCompanyId { get; set; }
        public byte NomineeRelationShipId { get; set; }
        public int PolicyCancelReasonId { get; set; }
        public byte IRDACommMonthCycleId { get; set; }
        public short DSAManageBy { get; set; }
        public Nullable<byte> DSACategoryId { get; set; }
        public short RTOZoneId { get; set; }
        public byte VehicleClassId { get; set; }
        public int NCBId { get; set; }
        public short TeleCallerId { get; set; }
        public string CustomerType { get; set; }
        public string Expr1 { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<int> CubicCapacity { get; set; }
        public Nullable<int> SeatingCapacity { get; set; }
        public Nullable<int> GVW { get; set; }
        public string ChassisNo { get; set; }
        public string EngineNo { get; set; }
        public Nullable<int> CNGIDV { get; set; }
        public Nullable<int> AssessoriesIDV { get; set; }
        public Nullable<int> LoyaltyCounter { get; set; }
        public Nullable<int> NoAdult { get; set; }
        public Nullable<int> NoChild { get; set; }
        public Nullable<decimal> SpecialDiscount { get; set; }
        public Nullable<decimal> Loading { get; set; }
        public Nullable<decimal> ServiceTax { get; set; }
        public string NomineeName { get; set; }
        public Nullable<byte> NomineeAge { get; set; }
        public Nullable<byte> NomineeGender { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> Exshowroom { get; set; }
        public string PAN { get; set; }
        public Nullable<int> VehicleIDV { get; set; }
        public Nullable<int> TotalIDV { get; set; }
        public Nullable<int> AddonOD { get; set; }
        public string PolicyRemarks { get; set; }
        public Nullable<System.DateTime> PolicyCancelDate { get; set; }
        public Nullable<short> DSAManagedBy { get; set; }
        public Nullable<int> TotalOD { get; set; }
        public string GSTIN { get; set; }
    }
}
