//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAllDatatypeInOne
    {
        public int InvitedDataId { get; set; }
        public int ReferalId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> DataTypeId { get; set; }
        public Nullable<int> VerticalSegmentId { get; set; }
        public Nullable<int> PermanentOwner { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<int> TemporaryOwner { get; set; }
        public Nullable<System.DateTime> TemporaryFromdate { get; set; }
        public Nullable<System.DateTime> TemporaryToDatedate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> FollowupDate { get; set; }
        public string ControlNo { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<int> Premiumoffered { get; set; }
    }
}
