//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDSAAllEmailId
    {
        public int SRNo { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> DSAId { get; set; }
        public string DSAName { get; set; }
    }
}
