//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPersonDataBirthdayWish
    {
        public string InsuredPersonName { get; set; }
        public Nullable<System.DateTime> InsuredDOB { get; set; }
        public string CustomerMobile1 { get; set; }
        public string CustomerEmail1 { get; set; }
        public byte BranchId { get; set; }
    }
}
