//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPendingCommission
    {
        public byte InsureCompanyId { get; set; }
        public Nullable<int> InsureCompanyODId { get; set; }
        public int ControlNo { get; set; }
        public string CompanyName { get; set; }
        public string NameInPolicy { get; set; }
        public Nullable<int> TPPremium { get; set; }
        public string CNType { get; set; }
        public Nullable<long> CoverNoteNo { get; set; }
        public string PolicyNo { get; set; }
        public string PolicyNoOD { get; set; }
        public string MakeYear { get; set; }
        public string ModelName { get; set; }
        public string RegistrationNo { get; set; }
        public string VehicleClass { get; set; }
        public string PolicyStatus { get; set; }
        public string EndorsementReason { get; set; }
        public string PolicyType { get; set; }
        public Nullable<System.DateTime> PolicyStartDate { get; set; }
        public Nullable<System.DateTime> PolicyStartDateOD { get; set; }
        public string PolicyPackageType { get; set; }
        public Nullable<int> OD { get; set; }
        public Nullable<int> GrossPremium { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string PolicyRemarks { get; set; }
        public string BusinessDoneBy { get; set; }
        public string VerticalName { get; set; }
        public int VerticleId { get; set; }
        public byte BranchId { get; set; }
    }
}
