//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewRenewPerformanceNonMotor
    {
        public int ControlNo { get; set; }
        public Nullable<short> FOSId { get; set; }
        public Nullable<short> TeleCallerId { get; set; }
        public byte InsureCompanyId { get; set; }
        public int DSAId { get; set; }
        public int ProductId { get; set; }
        public int VerticleId { get; set; }
        public byte BranchId { get; set; }
        public Nullable<System.DateTime> PolicyStartDate { get; set; }
        public Nullable<System.DateTime> PolicyEndDate { get; set; }
        public string CompanyName { get; set; }
        public string NameInPolicy { get; set; }
        public string DSAName { get; set; }
        public Nullable<int> RenewControlNo { get; set; }
        public string RenewalInsuranceCompany { get; set; }
        public string Telecaller { get; set; }
        public string FOS { get; set; }
        public string RenewalStatus { get; set; }
        public string BusinessDoneBy { get; set; }
        public int CustomerId { get; set; }
        public string AddressInPolicy { get; set; }
        public Nullable<int> TotalGrossPremium { get; set; }
        public Nullable<int> ShortFallTotalFull { get; set; }
        public Nullable<int> RenewPremium { get; set; }
        public string VerticalName { get; set; }
        public string ProductName { get; set; }
    }
}
