//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCustomerCareCrossSell
    {
        public int CustomerCallDataId { get; set; }
        public string VerticalName { get; set; }
        public string CompanyName { get; set; }
        public string CallTypeName { get; set; }
        public string ModelName { get; set; }
        public string MakeYear { get; set; }
        public string ProductName { get; set; }
        public Nullable<byte> Q1ResponsePost { get; set; }
        public string Q1CommentPost { get; set; }
        public Nullable<byte> Q2ResponsePost { get; set; }
        public string Q2CommentPost { get; set; }
        public Nullable<byte> Q3ResponsePost { get; set; }
        public string Q3CommentPost { get; set; }
        public string Q5CommentPost { get; set; }
        public Nullable<byte> CallStatusIdPost { get; set; }
        public Nullable<byte> SubStatusIdPost { get; set; }
        public Nullable<System.DateTime> FollowupDatePost { get; set; }
        public string FinalComment { get; set; }
        public Nullable<System.DateTime> LastCallDate { get; set; }
        public Nullable<int> CallTypeId { get; set; }
        public Nullable<int> CallDurationTypeId { get; set; }
        public Nullable<byte> Q4ResponsePost { get; set; }
        public string Q4CommentPost { get; set; }
        public Nullable<byte> Q5ResponsePost { get; set; }
        public Nullable<int> PolicyId { get; set; }
        public Nullable<int> ControlNo { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string NameInPolicy { get; set; }
        public Nullable<System.DateTime> PolicyStartDate { get; set; }
        public Nullable<int> DSAId { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<int> VerticalId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> InsureCompanyId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> MakeYearId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CrossSellInsureCompanyIdPost { get; set; }
        public Nullable<int> CrossSellVerticalIdPost { get; set; }
        public Nullable<System.DateTime> CrossSellExpiryDatePost { get; set; }
        public Nullable<int> CrossSellInsureCompanyId1Post { get; set; }
        public Nullable<int> CrossSellVerticalId1Post { get; set; }
        public Nullable<System.DateTime> CrossSellExpiryDate1Post { get; set; }
        public string DSAName { get; set; }
        public Nullable<int> CrossSellTelecallerIdPost { get; set; }
        public Nullable<int> CrossSellTelecallerId1Post { get; set; }
        public Nullable<int> CrossSellChkNewPost { get; set; }
        public Nullable<int> CrossSellChkNew1Post { get; set; }
        public Nullable<int> CrossSellInsureCompanyIdMid { get; set; }
        public Nullable<int> CrossSellVerticalIdMid { get; set; }
        public Nullable<System.DateTime> CrossSellExpiryDateMid { get; set; }
        public Nullable<int> CrossSellInsureCompanyId1Mid { get; set; }
        public Nullable<int> CrossSellVerticalId1Mid { get; set; }
        public Nullable<System.DateTime> CrossSellExpiryDate1Mid { get; set; }
        public Nullable<int> CrossSellTelecallerIdMid { get; set; }
        public Nullable<int> CrossSellTelecallerId1Mid { get; set; }
        public Nullable<int> CrossSellChkNewMid { get; set; }
        public Nullable<int> CrossSellChkNew1Mid { get; set; }
        public Nullable<int> CrossSellInsureCompanyIdPreRenew { get; set; }
        public Nullable<int> CrossSellVerticalIdPreRenew { get; set; }
        public Nullable<System.DateTime> CrossSellExpiryDatePreRenew { get; set; }
        public Nullable<int> CrossSellInsureCompanyId1PreRenew { get; set; }
        public Nullable<int> CrossSellVerticalId1PreRenew { get; set; }
        public Nullable<System.DateTime> CrossSellExpiryDate1PreRenew { get; set; }
        public Nullable<int> CrossSellTelecallerIdPreRenew { get; set; }
        public Nullable<int> CrossSellTelecallerId1PreRenew { get; set; }
        public Nullable<int> CrossSellChkNewPreRenew { get; set; }
        public Nullable<int> CrossSellChkNew1PreRenew { get; set; }
        public Nullable<byte> Q1ResponseMid { get; set; }
        public string Q1CommentMid { get; set; }
        public Nullable<byte> Q2ResponseMid { get; set; }
        public string Q2CommentMid { get; set; }
        public Nullable<byte> Q3ResponseMid { get; set; }
        public string Q3CommentMid { get; set; }
        public Nullable<byte> Q4ResponseMid { get; set; }
        public string Q4CommentMid { get; set; }
        public Nullable<byte> Q5ResponseMid { get; set; }
        public string Q5CommentMid { get; set; }
        public Nullable<byte> Q1ResponsePrerenew { get; set; }
        public string Q1CommentPrerenew { get; set; }
        public Nullable<byte> Q2ResponsePrerenew { get; set; }
        public string Q2CommentPrerenew { get; set; }
        public Nullable<byte> Q3ResponsePrerenew { get; set; }
        public string Q3CommentPrerenew { get; set; }
        public Nullable<byte> Q4ResponsePrerenew { get; set; }
        public string Q4CommentPrerenew { get; set; }
        public Nullable<byte> Q5ResponsePrerenew { get; set; }
        public string Q5CommentPrerenew { get; set; }
        public Nullable<byte> CallStatusIdMid { get; set; }
        public Nullable<byte> SubStatusIdMid { get; set; }
        public Nullable<System.DateTime> FollowupDateMid { get; set; }
        public Nullable<System.DateTime> FollowupTimeMid { get; set; }
        public Nullable<byte> CallStatusIdPrerenew { get; set; }
        public Nullable<byte> SubStatusIdPrerenew { get; set; }
        public Nullable<System.DateTime> FollowupDatePrerenew { get; set; }
        public Nullable<System.DateTime> FollowupTimePrerenew { get; set; }
    }
}
