//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManagement.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewRenewPerformance
    {
        public int ControlNo { get; set; }
        public Nullable<short> FOSId { get; set; }
        public Nullable<short> TeleCallerId { get; set; }
        public Nullable<int> OD { get; set; }
        public byte PrevInsCompanyTPId { get; set; }
        public int DSAId { get; set; }
        public int VerticleId { get; set; }
        public byte BranchId { get; set; }
        public Nullable<System.DateTime> PrevStartDateOD { get; set; }
        public Nullable<System.DateTime> PrevEndDateOD { get; set; }
        public string PrevInsCompanyNameTP { get; set; }
        public string NameInPolicy { get; set; }
        public string EngineNo { get; set; }
        public string ChassisNo { get; set; }
        public string ModelName { get; set; }
        public string RegistrationNo { get; set; }
        public string MakeYear { get; set; }
        public string ManufacturerName { get; set; }
        public string PrevPolicyNoTP { get; set; }
        public string DSAName { get; set; }
        public Nullable<int> RenewControlNo { get; set; }
        public string RenewInsCompanyNameTP { get; set; }
        public string Telecaller { get; set; }
        public string FOS { get; set; }
        public Nullable<int> RenewOD { get; set; }
        public string RenewalStatus { get; set; }
        public string BusinessDoneBy { get; set; }
        public int CustomerId { get; set; }
        public string AddressInPolicy { get; set; }
        public Nullable<System.DateTime> RenewEndDateOD { get; set; }
        public Nullable<System.DateTime> RenewStartDateOD { get; set; }
        public Nullable<int> RenewInsCompanyODID { get; set; }
        public string RenewPolicyNoOD { get; set; }
        public Nullable<System.DateTime> RenewStartDateTP { get; set; }
        public Nullable<int> ShortFallTotalFull { get; set; }
        public Nullable<System.DateTime> RenewEndDateTP { get; set; }
        public string RenewPolicyNoTP { get; set; }
        public Nullable<byte> RenewInsCompanyTPID { get; set; }
        public string RenewPackageType { get; set; }
        public string RenewPolicyTerm { get; set; }
        public string PrevPackageType { get; set; }
        public string PrevPolicyTerm { get; set; }
        public Nullable<System.DateTime> PrevStartDateTP { get; set; }
        public Nullable<System.DateTime> PrevEndDateTP { get; set; }
        public string PrevPolicyNoOD { get; set; }
        public string RenewInsCompanyNameOD { get; set; }
        public string PrevInsCompanyNameOD { get; set; }
        public Nullable<int> PrevInsCompanyODId { get; set; }
    }
}
